name: Build and deploy
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build ⛏
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Archive production artifact
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: /
  deploy:
    name: Deploy 🚀
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Download artifact
        uses: actions/download-artifact@main
        with: 
          name: dist
          path: /
      - name: Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with: 
          server: testing.neuronious.com
          username: ismail@testing.neuronious.com
          password: ${{ secrets.ftp_password }}
